[phases.setup]
nixPkgs = ["nodejs-22_x", "python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "npm start"
